
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install CP4WAIOPS PREREQUISITES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: ðŸ›°ï¸  START - CP4WAIOPS CATALOG - ONLINE
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Installing IBM CatalogSource - Online"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true

- name: ðŸ“£ OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerBottom")}}
      text: 'Installing {{current_cp4waiops_feature.kind}} - Installing IBM CatalogSource - Online'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  





# Create IBM Operator Catalog
- name:   ðŸš€ CP4WAIOPS CATALOG - Install IBM Operator Catalog - Online
  kubernetes.core.k8s:
    state: present
    template: ./templates/waiops/1_cat-ibm-catalog.j2







