
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install CP4WAIOPS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: ðŸ›°ï¸  START - CP4WAIOPS INSTALLATION
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Installing CP4WAIOps Instance"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: BannerTop
      text: 'Installing CP4WAIOPS: Module {{ansible_play_name}}'    
    EOF



  ignore_errors: true



- name:  ðŸš€ CP4WAIOPS INSTALL - Create Custom Profile ConfigMap
  shell: |
    oc apply -n {{ current_cp4waiops_cluster.project }} -f {{current_cp4waiops_feature.custom_size_file | default('none')}}
  register: kubectl_get_pods
  when: current_cp4waiops_feature.waiops_size | default('none') == "custom"



- name:  ðŸš€ CP4WAIOPS INSTALL - Install Custom Resource with Custom Profile - INSTALL CP4WAIOPS
  kubernetes.core.k8s:
    state: present
    template: './templates/waiops/4_waiops-install-template-custom.j2'
  when: current_cp4waiops_feature.waiops_size == "custom"





- name:  ðŸš€ CP4WAIOPS INSTALL - Install Custom Resource - INSTALL CP4WAIOPS
  kubernetes.core.k8s:
    state: present
    template: './templates/waiops/4_waiops-install-template.j2'
  when: current_cp4waiops_feature.waiops_size != "custom"

    