

global_config:
  environment_name: cp4waiops
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  create_cards: true
  create_ocp_items: true


openshift:
- name: "mycluster"
  ocp_version: "4.10"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: ibm-cloud-storage
    storage_type: custom
# Use file storate class provided as part of ROKS cluster
    ocp_storage_class_file: automatic
    ocp_storage_class_block: automatic
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold


cp4waiops:
- project: cp4waiops
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS AI Manager
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-aimanager
    kind: AIManager
    install: false
    # CP4WAIOPS Size of the install (small: PoC/Demo, tall: Production)
    waiops_size: small
    # Custom Sizing File (waiops_size must be set to "custom")
    custom_size_file: none
    # Name of the CP4WAIOPS instance
    waiops_name: ibm-cp-watson-aiops
    # Version of the catalog subscription
    subscription_channel: v3.5

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Install with CASE Files
    # --------------------------------------------------------------------------------------------------------------------------------------
    case_install: false
    case_github_url: "https://github.com/IBM/cloud-pak/raw/master/repo/case"
    case_name: ibm-cp-waiops
    case_version: 1.4.1
    case_inventory_setup: cpwaiopsSetup
    
    # --------------------------------------------------------------------------------------------------------------------------------------
    # CP4WAIOPS Pull Registires
    # --------------------------------------------------------------------------------------------------------------------------------------
    entitled_registry: cp.icr.io
    entitled_registry_user: cp
    catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  create_cards: true
  create_ocp_items: true

    
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS AI Manager Demo Content
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-aimanager-demo-content
    kind: AIManagerDemoContent
    install: true


    # ---------------------------------------------------------------------
    # TRAINING
    # Train the Models based on pre-canned content

    training_create_training_temporal: false

    training_load_data_logs: true
    training_create_training_logs: false
    training_run_training_logs: false

    training_load_data_snow: true
    training_create_training_snow: false
    training_run_training_snow: false

    training_load_data_metrics: true
    training_create_training_metrics: false
    training_run_training_metrics: false

    training_data_url: https://github.com/niklaushirt/
    training_data_repo: cp4waiops-trainingdata


    # ---------------------------------------------------------------------
    # TOPOLOGY
    # Install RobotShop Application
    install_robotshop: true
    # Install RobotShop K8s Observer
    install_robotshop_observer: false
    # Create Topology
    create_topology_templates: true
    create_topology_apps: false
    # Create RobotShop overlay topology
    install_robotshop_topology: true

    # ---------------------------------------------------------------------
    # RUNBOOKS
    # Install AWX and create Runbooks
    install_awx: true
    load_awx_playbooks: true
    integrate_awx_aimanager: false
    load_aimanager_runbooks: false
    create_runbook_policy: false


    # ---------------------------------------------------------------------
    # Demo UI
    install_demo_ui: true
    demoui_slack_url: https://app.slack.com/client/T0DBLALE5/C03MYASSZ2Q
    # demoui_slack_url: https://aiops-fry2953.slack.com/x-p1624757694871-3716524482480-3705437209041/messages/C01JZLFJFMJ
    demoui_slack_user: ibmaiopsdemo@gmail.com
    demoui_slack_pwd: P4ssw0rd!
    demoui_admin_mode: "true"
    demoui_simulation_mode: "true"

    demoui_aimanager_demo_user: demo
    demoui_aimanager_demo_pwd: P4ssw0rd!


    # ---------------------------------------------------------------------
    # LDAP
    install_ldap: true
    # ldap domain
    ldap_domain: ibm.com
    # ldap base
    ldap_base: dc=ibm,dc=com
    # ldap admin password
    ldap_admin_password: P4ssw0rd!
    # ldap namespace
    ldap_namespace: openldap
    # ldap namespace
    ldap_register: false

    # ---------------------------------------------------------------------
    # MISC PARAMETERS (you should not modify those)
    # Create external routes (needed to create demo content)
    create_external_routes: true

    # Create a valid ingress certificate (needed for Slack integration)
    create_valid_ingress_certificate: false

    # Create Policy for Story Creation
    create_story_policy: false

    # Create Kafka connection for Log inception (needed to create log anomalies in the demo environment)
    create_log_connection: true

    # Create Service Account
    create_account: true



    # ---------------------------------------------------------------------
    # OUTPUT
    # Print all logins
    print_logins: false
    # Open the relevant Web UIs
    open_web_ui: false




- project: cp4waiops-addons
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS ELK
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-elk
    kind: ELK
    install: true

  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS TURBONOMIC
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-turbonomic
    kind: Turbonomic
    install: false
    turbo_version: 8.6.6

    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic

  - name: cp4waiops-turbonomic-demo-content
    kind: TurbonomicDemoContent
    install: false
    turbo_password: P4ssw0rd!
    # ---------------------------------------------------------------------
    # Create Demo User
    create_user: false
    demo_user: demo
    demo_password: P4ssw0rd!
    # ---------------------------------------------------------------------
    # Create Groups
    group_vcenter_vms: true
    group_robotshop: true
    group_licensing: true

    # ---------------------------------------------------------------------
    # Create Targets
    target_instana: true
    # ---------------------------------------------------------------------
    # Create Memory and CPU hogs
    resource_hogs: true
    # ---------------------------------------------------------------------
    # Create Metrics server, DIF integration and RobotShop BuisnessApp
    metrics_dif: true

  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS INSTANA
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-instana
    kind: Instana
    install: true

    # ---------------------------------------------------------------------
    # INSTANA LICENSE
    sales_key: 'NONE'
    agent_key: 'NONE'

    # ---------------------------------------------------------------------
    # INSTANA ADMIN LOGIN
    initial_admin_user: "admin@instana.local"
    initial_admin_pass: 'P4ssw0rd!'
    
    # ---------------------------------------------------------------------
    # INSTALL INSTANA AGENT
    install_agent: true

    # --------------------------------------------------------------------------------------------------------------------------------------
    # INTEGRATIONS
    integrate_aimanager: false
    #integrate_turbonomic: true
    
    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic



# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS USAGE
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
#storage_class_file: automatic
#storage_class_file: ibmc-file-gold-gid               # ROKS
#storage_class_file: ocs-storagecluster-cephfs        # ODF
#storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
#storage_class_file: rook-cephfs                      # FYRE
#storage_class_file: nfs-client                       # TEC

#storage_class_block: automatic
#storage_class_block: ibmc-block-gold                 # ROKS
#storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
#storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
#storage_class_block: rook-cephfs                     # FYRE
#storage_class_block: nfs-client                      # TEC

