---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


global_config:
  environment_name: sample
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest


openshift:
- name: "mycluster"
  ocp_version: "4.10"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: ibm-cloud-storage
    storage_type: custom
# Use file storate class provided as part of ROKS cluster
    ocp_storage_class_file: automatic
    ocp_storage_class_block: automatic
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold


cp4waiops:
- project: cp4waiops-evtmgr
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Event Manager
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-eventmanager
    kind: EventManagerDemoContent
    install: true



