---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

cp4waiops:
- project: cp4waiops
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS AI Manager
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-aimanager
    kind: AIManager
    install: true
    # CP4WAIOPS Size of the install (small: PoC/Demo, tall: Production)
    waiops_size: small
    # Name of the CP4WAIOPS instance
    waiops_name: ibm-cp-watson-aiops
    # Version of the catalog subscription
    subscription_channel: v3.3

  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS AI Manager Demo Content
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-aimanager-demo-content
    kind: AIManagerDemoContent
    install: true
    # ldap domain
    ldap_domain: ibm.com
    # ldap base
    ldap_base: dc=ibm,dc=com
    # ldap admin password
    ldap_admin_password: P4ssw0rd!





- project: cp4waiops-evtmgr
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Event Manager
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-eventmanager
    kind: EventManager
    install: true
    # Version of the catalog subscription
    subscription_channel: v1.10
    starting_csv: noi.v1.6.0





- project: cp4waiops-infra
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Infrastructure Management
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-infrastructure-management
    kind: InfrastructureManagement
    install: true
    # Version of the catalog subscription
    subscription_channel: v3.3
    #subscription_channel: 3.4-dev




- project: cp4waiops-addons
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS ELK
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-elk
    kind: ELK
    install: true


  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS TURBONOMIC
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-turbonomic
    kind: Turbonomic
    install: true



# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS GLOBAL CONFIGURATION
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
storage_class_file: automatic
#storage_class_file: ibmc-file-gold-gid               # ROKS
#storage_class_file: ocs-storagecluster-cephfs        # ODF
#storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
#storage_class_file: rook-cephfs                      # FYRE
#storage_class_file: nfs-client                       # TEC
storage_class_block: automatic
#storage_class_block: ibmc-block-gold                 # ROKS
#storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
#storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
#storage_class_block: rook-cephfs                     # FYRE
#storage_class_block: nfs-client                      # TEC



# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Pull Registires
# --------------------------------------------------------------------------------------------------------------------------------------

entitled_registry: cp.stg.icr.io
entitled_registry_user: cp
catalog_image: icr.io/cpopen/ibm-operator-catalog:latest


#Version of your OCP Cluster (override by setting manually - 4.6, 4.7,...)
ocp_major_version: automatic
