---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

cp4waiops:
- project: cp4waiops
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS AI Manager Demo Content
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-aimanager-demo-content
    kind: AIManagerDemoContent
    install: true

    # TRAINING
    # Train the Models based on pre-canned content
    train_models: true
    training_data_url: https://github.com/niklaushirt/
    training_data_repo: cp4waiops-trainingdata

    # TOPOLOGY
    # Install RobotShop Application
    install_robotshop: true
    # Create Topology
    create_topology: true
    # Create RobotShop overlay topology
    install_robotshop_topology: true

    # RUNBOOKS
    # Install AWX and create Runbooks
    create_runbooks: true
   
    # Demo UI
    install_demo_ui: true
    demoui_slack_url: https://aiops-fry2953.slack.com/x-p1624757694871-3716524482480-3705437209041/messages/C01JZLFJFMJ
    demoui_slack_user: ibmaiopsdemo@gmail.com
    demoui_slack_pwd: P4ssw0rd!
    demoui_admin_mode: "true"
    demoui_aimanager_demo_user: demo
    demoui_aimanager_demo_pwd: P4ssw0rd!

    # OUTPUT
    # Print all logins
    print_logins: true
    # Open the relevant Web UIs
    open_web_ui: true

    # LDAP
    install_ldap: true
    # ldap domain
    ldap_domain: ibm.com
    # ldap base
    ldap_base: dc=ibm,dc=com
    # ldap admin password
    ldap_admin_password: P4ssw0rd!

    # PARAMETERS (you should not modify those)
    # Create external routes (needed to create demo content)
    create_external_routes: true
    # Create a valid ingress certificate (needed for Slack integration)
    create_valid_ingress_certificate: true
    # Create Policy for Story Creation
    create_story_policy: true
    # Create Kafka connection for Log inception (needed to create log anomalies in the demo environment)
    create_log_connection: true
    # Create Service Account
    create_account: true

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS GLOBAL CONFIGURATION
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
storage_class_file: automatic
#storage_class_file: ibmc-file-gold-gid               # ROKS
#storage_class_file: ocs-storagecluster-cephfs        # ODF
#storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
#storage_class_file: rook-cephfs                      # FYRE
#storage_class_file: nfs-client                       # TEC
storage_class_block: automatic
#storage_class_block: ibmc-block-gold                 # ROKS
#storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
#storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
#storage_class_block: rook-cephfs                     # FYRE
#storage_class_block: nfs-client                      # TEC



# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Pull Registires
# --------------------------------------------------------------------------------------------------------------------------------------
entitled_registry: cp.icr.io
entitled_registry_user: cp
catalog_image: icr.io/cpopen/ibm-operator-catalog:latest


#Version of your OCP Cluster (override by setting manually - 4.6, 4.7,...)
ocp_major_version: automatic
