
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install CP4WAIOPS PREREQUISITES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: ðŸ›°ï¸  START - AI MANAGER CATALOG - ONLINE
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Installing IBM CatalogSource - Online"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true





# Create IBM Operator Catalog
- name:   ðŸš€ AIMANAGER CATALOG - Install IBM Operator Catalog - Online
  community.kubernetes.k8s:
    state: present
    template: ./templates/waiops/1_cat-ibm-catalog.j2



- name:   ðŸš€ AIMANAGER CATALOG - Freeze IBM Operator Catalog version (if enabled)
  shell: |

    export FREEZE={{current_cp4waiops_feature.freeze_catalog | default("false") }}
    if [[ $FREEZE == "true" ]];
    then
      echo " Freezing Catalog Version"
      IMGDIGEST=`oc get pods -n openshift-marketplace -l=olm.catalogSource=ibm-operator-catalog --no-headers -o=jsonpath="{.items[0].status.containerStatuses[0].imageID}" -n openshift-marketplace` && \
      oc patch catalogsource ibm-operator-catalog -n openshift-marketplace --type=json -p "[{ "op": "test", "path": "/spec/image", "value": "\"icr.io/cpopen/ibm-operator-catalog:latest\"" }, { "op": "replace", "path": "/spec/image", "value": "\"$IMGDIGEST\"" }]"
    else
      echo " NOT Freezing Catalog Version"
    fi
  ignore_errors: true



