

- name: ğŸ›°ï¸  START - LOAD METRIC TRAINING DATA
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Load Metric Training Data into Cassandra"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true

- name: ğŸŸ¡ğŸŸ¡ğŸŸ¡  OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: {{global_config.position_ocp_notifications | default("BannerBottom")}}
      text: 'Installing {{current_cp4waiops_feature.kind}} - Load Metric Training Data into Cassandra'    
    EOF
  ignore_errors: true
  when: global_config.create_ocp_notifications | default(true) == true  


- name: ğŸ“¥ TRAINING LOAD METRIC - DELETE EXISTING JOB
  kubernetes.core.k8s:
    state: absent
    namespace: default
    template: ./templates/training/load-job-metric.j2


- name: ğŸ“¥ TRAINING LOAD METRIC - CREATE CLUSTERROLE
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: ./templates/training/default-clusterrole.yaml
    

- name: ğŸ“¥ TRAINING LOAD METRIC - LOAD CASSANDRA METRIC DATA 
  kubernetes.core.k8s:
    state: present
    namespace: default
    template: ./templates/training/load-job-metric.j2
  