

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Patching some stuff
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    

- name: ðŸ›°ï¸  START - OCP CONSOLE
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Create Openshift WebConsole Menu Item"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: BannerTop
      text: 'Installing {{current_cp4waiops_feature.kind}} - Create Openshift WebConsole Menu Item'    
    EOF



  ignore_errors: true
   


- name: ðŸŒ OCP CONSOLE - Create Openshift WebConsole Menu Item
  shell: |
    export WAIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $WAIOPS_NAMESPACE-demo-ui $WAIOPS_NAMESPACE-demo-ui  -o jsonpath="{['spec']['host']}")|| true

    cat <<EOF | oc apply -f -
      apiVersion: console.openshift.io/v1
      kind: ConsoleLink
      metadata:
        name: cp4waiops-aimanager-demo
      spec:
        applicationMenu:
          imageURL: >-
            https://raw.githubusercontent.com/niklaushirt/cp4waiops-deployer/main/doc/pics/icons/demo-icon.svg
          section: CP4WAIOps Demo
        href: >-
          https://$appURL
        location: ApplicationMenu
        text: CP4WAIOps Demo UI
    EOF
  ignore_errors: true


