

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Patching some stuff
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
    

- name: ðŸ›°ï¸  START - OCP MENU
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Create Openshift WebConsole Menu Item"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#ffd500'
      color: '#000'
      location: BannerTop
      text: 'Installing CP4WAIOPS: Module {{ansible_play_name}}'    
    EOF



  ignore_errors: true
   




- name: ðŸŒ OCP MENU - Create Openshift WebConsole Menu Item - Turbonomic
  shell: |
    appURL=$(oc get route -n turbonomic nginx -o jsonpath={.spec.host})|| true

    cat <<EOF | oc apply -f -
      apiVersion: console.openshift.io/v1
      kind: ConsoleLink
      metadata:
        name: cp4waiops-turbonomic
      spec:
        applicationMenu:
          imageURL: >-
            https://raw.githubusercontent.com/niklaushirt/cp4waiops-deployer/main/doc/pics/icons/turbo-icon.svg
          section: CP4WAIOps Addons
        href: >-
          https://$appURL
        location: ApplicationMenu
        text: Turbonomic
    EOF
  ignore_errors: true

