---

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Generic Event Webhook 
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: ðŸ›°ï¸  START - AIOPS DEMO UI
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Create DEMO UI"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: yes



- name: ðŸš€ DEMO-UI - Delete old instance (ignore errors))
  shell: |
    oc delete deployment -n {{current_cp4waiops_cluster.project}} waiops-demo-ui-python --ignore-not-found
    oc delete job -n {{current_cp4waiops_cluster.project}} demo-ui-python-create-config --ignore-not-found
    oc delete job -n {{current_cp4waiops_cluster.project}} demo-ui-python-create-config-events --ignore-not-found
    oc delete job -n {{current_cp4waiops_cluster.project}} demo-ui-python-create-config-logs --ignore-not-found
    oc delete job -n {{current_cp4waiops_cluster.project}} demo-ui-python-create-config-metrics --ignore-not-found
    oc delete cm -n {{current_cp4waiops_cluster.project}} demo-ui-python-config --ignore-not-found
    oc delete cm -n {{current_cp4waiops_cluster.project}} demo-ui-python-config-events --ignore-not-found
    oc delete cm -n {{current_cp4waiops_cluster.project}} demo-ui-python-config-logs --ignore-not-found
    oc delete cm -n {{current_cp4waiops_cluster.project}} demo-ui-python-config-metrics --ignore-not-found
  register: CERT_ELEMENT
  ignore_errors: yes


- name: ðŸš€ DEMO-UI - Create CP4WAIOPS Demo UI Configuration
  kubernetes.core.k8s:
    state: present
    template: ./templates/waiops-demo-ui/create-cp4waiops-demo-cm.j2

# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for Demo UI Configuration being ready
# --------------------------------------------------------------------------------------------------------------------------------------
- name: ðŸ•¦ DEMO-UI - Wait for Demo UI Configuration being ready
  shell: oc get cm -n {{current_cp4waiops_cluster.project}} demo-ui-python-config --ignore-not-found --no-headers|grep -c ""
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "1"
  retries: 500
  delay: 15


- name: ðŸš€ DEMO-UI - Create CP4WAIOPS Demo UI Deployment
  kubernetes.core.k8s:
    state: present
    template: ./templates/waiops-demo-ui/create-cp4waiops-demo-deploy.j2


# Wait for Demo UI being ready
# --------------------------------------------------------------------------------------------------------------------------------------
- name: ðŸ•¦ DEMO-UI - Wait for Demo UI being ready
  shell: oc get pod -n {{current_cp4waiops_cluster.project}} |grep waiops-demo-ui-python|grep "1/1"|grep -v "Terminating"|grep -c ""
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "1"
  retries: 50
  delay: 15



- name: Log
  shell: |
    export MESSAGE="Installing DEMO UI"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "              ðŸ“¥ DEMO UI Login:"  >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo ""  >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo "                ðŸŒ URL:      http://$(oc get route -n {{current_cp4waiops_cluster.project}} waiops-demo-ui-python -o jsonpath={.spec.host})"  >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo "                ðŸ” Token:    $(oc get cm -n {{current_cp4waiops_cluster.project}} demo-ui-python-config -o jsonpath='{.data.TOKEN}' && echo)"  >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: yes

