
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install Turbonomic
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Install Turbonomic Demo Content
# --------------------------------------------------------------------------------------------------------------------------------------

- name: ðŸ›°ï¸  START - INSTALL TURBONOMIC
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: Log
  shell: |
    export MESSAGE="Installing TURBONOMIC Demo Content"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true



- name: ðŸš€ TURBONOMIC - Get ROUTE
  shell: |
    export TURBO_URL=$(oc get route -n turbonomic api -o jsonpath={.spec.host})
    echo $TURBO_URL
  ignore_errors: true
  register: output
        
- name: ðŸš€ TURBONOMIC - Set ROUTE - {{ output.stdout_lines }} 
  set_fact: TURBO_URL={{ output.stdout_lines[0] }} 



- name: ðŸš€ TURBONOMIC - Login
  shell: |
    echo "------------------------------------------------------------------------------------------------------------------------------"
    echo " ðŸ“¥ Initialization"
    export TURBO_PASSWORD={{current_cp4waiops_feature.turbo_password}}
    export TURBO_URL={{TURBO_URL}}

    while [[ `curl -XPOST -s -k -c /tmp/cookies -H 'accept: application/json' "https://{{TURBO_URL}}/api/v3/login?hateoas=true" -d "username=administrator&password=$TURBO_PASSWORD"` =~ "InvalidCredentialsException" ]]
    do
      echo "Waiting for Turbo Init"
      sleep 15
    done
  ignore_errors: true
  register: output
  args:
    executable: /bin/bash
- name: ðŸŸ£  DEBUG
  debug:
    var: output.stdout_lines
    verbosity: 1
        


