current_cp4waiops_cluster:
  project: cp4waiops


current_cp4waiops_feature:
  kind: AIManagerDemo

  
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS AI MANAGER CONFIGURATION
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Size of the install (small: PoC/Demo, tall: Production)
  waiops_size: small
  # Name of the CP4WAIOPS instance
  waiops_name: ibm-cp-watson-aiops
  # Version of the catalog subscription
  subscription_channel: v3.5


  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS AI MANAGER Demo Content CONFIGURATION
  # --------------------------------------------------------------------------------------------------------------------------------------
  # ldap domain
  ldap_domain: ibm.com
  # ldap base
  ldap_base: dc=ibm,dc=com
  # ldap admin password
  ldap_admin_password: P4ssw0rd!
  demoui_slack_url: https://aiops-fry2953.slack.com/x-p1624757694871-3716524482480-3705437209041/messages/C01JZLFJFMJ
  demoui_slack_user: ibmaiopsdemo@gmail.com
  demoui_slack_pwd: P4ssw0rd!
  demoui_admin_mode: "true"
  demoui_aimanager_demo_user: demo
  demoui_aimanager_demo_pwd: P4ssw0rd!














# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS GLOBAL CONFIGURATION
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
config_file:

  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Storage Classes
  # --------------------------------------------------------------------------------------------------------------------------------------

  # Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
  storage_class_file: automatic
  #storage_class_file: ibmc-file-gold-gid               # ROKS
  #storage_class_file: ocs-storagecluster-cephfs        # ODF
  #storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
  #storage_class_file: rook-cephfs                      # FYRE
  #storage_class_file: nfs-client                       # TEC
  storage_class_block: automatic
  #storage_class_block: ibmc-block-gold                 # ROKS
  #storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
  #storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
  #storage_class_block: rook-cephfs                     # FYRE
  #storage_class_block: nfs-client                      # TEC



  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest


  #Version of your OCP Cluster (override by setting manually - 4.6, 4.7,...)
  ocp_major_version: automatic

