

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ¬©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Turbonomic
#  - Turbonomic Demo Content
#     - Demo User
#     - RobotShop Demo App with synthetic metric
#     - Instana target (if Instana is installed - you have to enter the API Token Manually)
#     - Groups for vCenter and RobotShop
#     - Groups for licensing
#     - Resource Hogs
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name: ‚ú¥Ô∏è ‚ú¥Ô∏è ‚ú¥Ô∏è INSTALLATION MODULE START - {{current_cp4waiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      üü°üü°üü°üü°üü°  üöÄ CloudPak for Watson AIOps - INSTALLING {{current_cp4waiops_feature.kind}} üü°üü°üü°üü°üü°                                                        "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Check Login
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************



- name: üü°üü°üü°  OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    export WAIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $WAIOPS_NAMESPACE-demo-ui $WAIOPS_NAMESPACE-demo-ui  -o jsonpath="{['spec']['host']}")|| true

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#00B7FF'
      color: '#fff'
      location: BannerTop
      text: 'Installing Feature {{current_cp4waiops_feature.kind}}'    
    EOF
  ignore_errors: true



- name:   üöÄ INITIALIZATION - Get Cluster FQDN
  shell: |
    CLUSTER_ROUTE=$(oc get routes console -n openshift-console | tail -n 1 2>&1 ) 
    CLUSTER_FQDN=$( echo $CLUSTER_ROUTE | awk '{print $2}')
    echo ${CLUSTER_FQDN##*console.}
  register: CLUSTER_NAME


- name:   üöÄ INITIALIZATION - Check Cluster Connectivity
  fail: msg="You must be logged in to the server!"
  when: CLUSTER_NAME.stdout==""



- name: üü£ Installing {{current_cp4waiops_feature.kind}} with the following configuration
  debug:
    var: current_cp4waiops_feature


- name:  üü£ Storage Class Parameters - SPECIFIC INSTANCE"
  debug:
    msg:
    - "** Installation Options for SPECIFIC INSTANCE ***********************************************************************"
    - " Storage Class File Override:      {{ current_cp4waiops_feature.storage_class_file}}"
    - " Storage Class Block Override:     {{ current_cp4waiops_feature.storage_class_block}}"
    - ""
  when: current_cp4waiops_feature.storage_class_file is defined


- name:  üü£ Storage Class Parameters - GLOBAL"
  debug:
    msg:
    - "** Installation Options from GLOBAL ***********************************************************************"
    - " Storage Class File Override:      {{ ocp_storage_class_file }}"
    - " Storage Class Block Override:     {{ ocp_storage_class_block }}"
    - ""
  when: current_cp4waiops_feature.storage_class_file is not defined and ocp_storage_class_file is defined




# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Check Encrypted Licenses
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: Get Licenses 
  block:

  - name: üíæ SET sales_key from Config File - {{current_cp4waiops_feature.sales_key | default("NONE")}} 
    set_fact: current_sales_key={{current_cp4waiops_feature.sales_key| default("NONE")}}


  - name: üíæ SET agent_key from  Config File  - {{current_cp4waiops_feature.agent_key | default("NONE")}} 
    set_fact: current_agent_key={{current_cp4waiops_feature.agent_key| default("NONE")}}



- name: Decrypt Licenses 
  block:
  - name: Create Token File
    shell: |
      echo {{global_config.license_token}} > /tmp/pwd.yaml
    ignore_errors: true


  - name: Get License from Vault
    shell: |
      OS=$(uname -s | tr '[:upper:]' '[:lower:]')
      if [ "${OS}" == "darwin" ]; then
            echo "MAC"
            LICENSE_FILE=$(pwd)"/roles/cp4waiops-instana/vars/lic.yaml"
      else
            LICENSE_FILE="{{role_path}}/vars/lic.yaml"
      fi    
      echo $LICENSE_FILE
      ansible-vault decrypt --vault-password-file /tmp/pwd.yaml --output /tmp/license.yaml "$LICENSE_FILE"
    register: OUTPUT
    ignore_errors: true


  - name: Include License from Vault
    ansible.builtin.include_vars:
      file: /tmp/license.yaml
      name: licenses
    ignore_errors: true

  - name: Cleanup
    shell: |
      rm /tmp/pwd.yaml
      rm /tmp/license.yaml
    ignore_errors: true

      
  - name: üíæ SET sales_key from Vault
    set_fact: current_sales_key={{licenses.sales_key }} 

  - name: üíæ SET agent_key from Vault
    set_fact: current_agent_key={{licenses.agent_key }} 




  when: global_config.license_token is defined 




- name:  üü£ Check Sales and Agent Key"
  debug:
    msg:
    - "** Missing License Information ***********************************************************************"
    - " Sales Key:      {{ current_sales_key}}"
    - " Agent Key:      {{ current_agent_key}}"
    - "‚ùå Skipping installation...."
    - ""
  when: current_sales_key == "NONE" or current_agent_key == "NONE"




- name:  üü¢ Sales and Agent Key - OK"
  debug:
    msg:
    - "** License Information ***********************************************************************"
    - " Sales Key:      {{ current_sales_key}}"
    - " Agent Key:      {{ current_agent_key}}"
    - " ‚úÖ OK...."
    - ""
    verbosity: 2
  when: current_sales_key != "NONE" or current_agent_key != "NONE"




- name: Install Instana if sales and agent key provided
  block:

  # ---------------------------------------------------------------------------------------------------------------------------------------------------"
  # INITIALIZATION
  # ---------------------------------------------------------------------------------------------------------------------------------------------------"
  # Placeholder for customization
  - name: üü°üü°üü° Initialize Custom Hook
    include_tasks: 00_init-custom-hook.yaml

  # Initialize Logging
  - name: üü°üü°üü° Initialize Logging
    include_tasks: "{{role_path}}/../cp4waiops-global/tasks/01_init-logging.yaml"

  - name: üü°üü°üü° Get Storage Class
    include_tasks: "{{role_path}}/../cp4waiops-global/tasks/05_init-get-storage-class.yaml"

    
  # Start block
  - name: üü°üü°üü° Start Logging
    include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90-log-start.yaml"


  # ---------------------------------------------------------------------------------------------------------------------------------------------------"
  # INSTALL INSTANA
  # ---------------------------------------------------------------------------------------------------------------------------------------------------"
  # Install INSTANA
  - name: üü°üü°üü° Install Instana
    include_tasks: 10_addons-instana.yaml


  # Install INSTANA AGENT
  - name: üü°üü°üü° Install Instana Agent
    include_tasks: 11_addons-instana-agent.yaml
    when: current_cp4waiops_feature.install_agent == true


  # Install INSTANA CP4WAIOps Connection
  - name: üü°üü°üü° Install CP4WAIOps to Instana Connection
    include_tasks: 12_addons-instana-create-connections.yaml
    when: current_cp4waiops_feature.integrate_cp4waiops == true


  - name: üü°üü°üü° Restart Demo UI
    include_tasks: 21_addons-instana-restart-demoui.yaml


  - name: üü°üü°üü° Install OCP Menu Item
    include_tasks: 91_addons-instana-create-ocp-tools-menu.yaml
    when: global_config.create_ocp_items | default(true) == true  

  # Update CP4WAIOps Cards
  - name: üü°üü°üü° Update CP4WAIOps Cards
    include_tasks: "{{role_path}}/../cp4waiops-global/tasks/99_update_cards.yaml"


  - name: üåè INSTANA - LOGINS
    shell: |
      export DEMOUI_ROUTE=$(oc get routes -n instana-core dev-aiops  -o jsonpath="{['spec']['host']}")
      echo "                üåè URL:       http://$DEMOUI_ROUTE"
      echo ""
      echo "                üßë‚Äçü¶≥ USER:      {{current_cp4waiops_feature.instana_admin_user}}"
      echo "                üîê LOGIN:     {{current_cp4waiops_feature.instana_admin_pass  | default('using global')}}"
    ignore_errors: true
    register: LOGINS


  - name: üåè INSTANA - LOGINS
    debug: 
      var: LOGINS.stdout_lines

  - name: Log
    shell: |
      export MESSAGE=" üåè INSTANA - LOGINS"
      export currentDate=$(date +%Y-%m-%d_%H:%M)
      echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
      echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
      appURL=$(oc get routes -n instana-core dev-aiops  -o jsonpath="{['spec']['host']}")|| true
      echo "            üì• Demo UI:"     >> ../install_{{current_cp4waiops_feature.kind}}.log
      echo "    "   >> ../install_{{current_cp4waiops_feature.kind}}.log
      echo "                üåè URL:           http://$appURL/"  >> ../install_{{current_cp4waiops_feature.kind}}.log
      echo "                üßë‚Äçü¶≥ USER:          {{current_cp4waiops_feature.instana_admin_user}}"  >> ../install_{{current_cp4waiops_feature.kind}}.log
      echo "                üîê PASSWORD:      {{current_cp4waiops_feature.instana_admin_pass| default('using global')}}"  >> ../install_{{current_cp4waiops_feature.kind}}.log
      echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
      echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    ignore_errors: true
  # ---------------------------------------------------------------------------------------------------------------------------------------------------"
  # CHECKS
  # ---------------------------------------------------------------------------------------------------------------------------------------------------"

  #when: current_sales_key != "NONE" and current_agent_key != "NONE"
  ignore_errors: true


- name: üü°üü°üü° End Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/91-log-end.yaml"


- name: üü°üü°üü°  OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    export WAIOPS_NAMESPACE=$(oc get po -A|grep aiops-orchestrator-controller |awk '{print$1}')
    appURL=$(oc get routes -n $WAIOPS_NAMESPACE-demo-ui $WAIOPS_NAMESPACE-demo-ui  -o jsonpath="{['spec']['host']}")|| true

    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification
    spec:
      backgroundColor: '#009a00'
      color: '#fff'
      link:
        href: "https://$appURL"
        text: DemoUI
      location: BannerTop
      text: 'CP4WAIOPS is installed in this cluster. Access the DemoUI here:'
    EOF
  ignore_errors: true



- name: ‚úÖ INSTALLATION MODULE DONE - {{current_cp4waiops_feature.kind}}
  debug: 
    msg:  

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       ‚úÖ CloudPak for Watson AIOps - DONE INSTALLING {{current_cp4waiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
