

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  Â©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - Turbonomic
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 
 
 
- name: âœ´ï¸ âœ´ï¸ âœ´ï¸ INSTALLATION MODULE START - {{current_cp4waiops_feature.kind}}
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "      ðŸš€ CloudPak for Watson AIOps - INSTALLING {{current_cp4waiops_feature.kind}}                                                                                          "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"



- name: ðŸŸ£ Installing {{current_cp4waiops_feature.kind}} with the following configuration
  debug:
    var: current_cp4waiops_feature


- name:  ðŸŸ£ Storage Class Parameters - SPECIFIC INSTANCE"
  debug:
    msg:
    - "** Installation Options for SPECIFIC INSTANCE ***********************************************************************"
    - " Storage Class File Override:      {{ current_cp4waiops_feature.storage_class_file}}"
    - " Storage Class Block Override:     {{ current_cp4waiops_feature.storage_class_block}}"
    - " Storage Class InfraManagement:    {{ current_cp4waiops_feature.storage_class_file}}"
    - ""
  when: current_cp4waiops_feature.storage_class_file is defined


- name:  ðŸŸ£ Storage Class Parameters - GLOBAL"
  debug:
    msg:
    - "** Installation Options from GLOBAL ***********************************************************************"
    - " Storage Class File Override:      {{ all_config.openshift[0].openshift_storage[0].ocp_storage_class_file}}"
    - " Storage Class Block Override:     {{ all_config.openshift[0].openshift_storage[0].ocp_storage_class_block}}"
    - " Storage Class InfraManagement:    {{ all_config.openshift[0].openshift_storage[0].ocp_storage_class_file}}"
    - ""
  when: current_cp4waiops_feature.storage_class_file is not defined and all_config.openshift[0].openshift_storage[0].ocp_storage_class_file is defined


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
- name: ðŸ“¥ Init Custom Hook
  include_tasks: 00_init-custom-hook.yaml

# Initialize Logging
- name: ðŸ“¥ Init Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/01_init-logging.yaml"

- name: ðŸ“¥ Get Storage Class
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/05_init-get-storage-class.yaml"

  
# Start block
- name: ðŸ“¥ Start Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/90-log-start.yaml"




# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL INSTANA
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install INSTANA
- name: ðŸ“¥ Install Instana
  include_tasks: 10_addons-instana.yaml


# Install INSTANA AGENT
- name: ðŸ“¥ Install Instana Agent
  include_tasks: 11_addons-instana-agent.yaml
  when: current_cp4waiops_feature.install_agent == true

- name: ðŸ“¥ Install OCP Menu Item
  include_tasks: 91_addons-instana-create-ocp-tools-menu.yaml



- name: ðŸŒ INSTANA - LOGINS
  shell: |
    export DEMOUI_ROUTE=$(oc get routes -n instana-core dev-aiops  -o jsonpath="{['spec']['host']}")
    echo "                ðŸŒ URL:       http://$DEMOUI_ROUTE"
    echo ""
    echo "                ðŸ§‘â€ðŸ¦³ USER:      {{initial_admin_user}}"
    echo "                ðŸ” LOGIN:     {{initial_admin_pass}}"
  ignore_errors: true
  register: LOGINS


- name: ðŸŒ INSTANA - LOGINS
  debug: 
    var: LOGINS.stdout_lines

- name: Log
  shell: |
    export MESSAGE=" ðŸŒ INSTANA - LOGINS"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    appURL=$(oc get routes -n instana-core dev-aiops  -o jsonpath="{['spec']['host']}")|| true
    echo "            ðŸ“¥ Demo UI:"     >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo "    "   >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo "                ðŸŒ URL:           http://$appURL/"  >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo "                ðŸ§‘â€ðŸ¦³ USER:          {{initial_admin_user}}"  >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo "                ðŸ” USER:          {{initial_admin_pass}}"  >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: true



- name: ðŸ“¥ End Logging
  include_tasks: "{{role_path}}/../cp4waiops-global/tasks/91-log-end.yaml"





- name: âœ… INSTALLATION MODULE DONE - {{current_cp4waiops_feature.kind}}
  debug: 
    msg:  

    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       âœ… CloudPak for Watson AIOps - DONE INSTALLING {{current_cp4waiops_feature.kind}}                                                                                 "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
